"""create messages table

Revision ID: 89b47f1e8061
Revises: fae6dc3961e1
Create Date: 2025-09-18 17:18:12.268308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b47f1e8061'
down_revision = 'fae6dc3961e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
